# Generated by Django 4.2.8 on 2025-12-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='기타', max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(default='중간', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.CharField(default='적당량', max_length=100),
        ),
    ]
